_format_version: "1.1"

services:
  - name: auth
    url: http://auth:9999
    routes:
      - paths:
          - /auth/v1
        strip_path: true
    plugins:
      - name: cors
        config:
          origins:
            - http://localhost:5173
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            - PATCH
          headers:
            - Accept
            - Accept-Language
            - Content-Language
            - Content-Type
            - Authorization
            - x-client-info
            - apikey
            - x-address-guid
            - x-supabase-api-version
          exposed_headers:
            - Content-Length
            - Content-Range
          max_age: 3600
          credentials: true
