/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import type * as Fetcher from "./chronosFetcher";
import { chronosFetch } from "./chronosFetcher";
import type * as Schemas from "./chronosSchemas";

export type GetHealthError = Fetcher.ErrorWrapper<undefined>;

export const getHealth = (signal?: AbortSignal) =>
  chronosFetch<undefined, GetHealthError, undefined, {}, {}, {}>({
    url: "/api/health",
    method: "get",
    signal,
  });

export type SignupError = Fetcher.ErrorWrapper<undefined>;

export type SignupResponse = {
  message?: string;
};

export type SignupVariables = {
  body: Schemas.SignupRequest;
};

export const signup = (variables: SignupVariables, signal?: AbortSignal) =>
  chronosFetch<SignupResponse, SignupError, Schemas.SignupRequest, {}, {}, {}>({
    url: "/api/auth/signup",
    method: "post",
    ...variables,
    signal,
  });

export type LoginError = Fetcher.ErrorWrapper<undefined>;

export type LoginVariables = {
  body: Schemas.LoginRequest;
};

export const login = (variables: LoginVariables, signal?: AbortSignal) =>
  chronosFetch<
    Schemas.AuthResponse,
    LoginError,
    Schemas.LoginRequest,
    {},
    {},
    {}
  >({ url: "/api/auth/login", method: "post", ...variables, signal });

export type RequestMagicLinkError = Fetcher.ErrorWrapper<undefined>;

export type RequestMagicLinkRequestBody = {
  email?: string;
};

export type RequestMagicLinkVariables = {
  body?: RequestMagicLinkRequestBody;
};

export const requestMagicLink = (
  variables: RequestMagicLinkVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    RequestMagicLinkError,
    RequestMagicLinkRequestBody,
    {},
    {},
    {}
  >({
    url: "/api/auth/request-magic-link",
    method: "post",
    ...variables,
    signal,
  });

export type MagicLoginQueryParams = {
  token: string;
};

export type MagicLoginError = Fetcher.ErrorWrapper<undefined>;

export type MagicLoginVariables = {
  queryParams: MagicLoginQueryParams;
};

export const magicLogin = (
  variables: MagicLoginVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    Schemas.AuthResponse,
    MagicLoginError,
    undefined,
    {},
    MagicLoginQueryParams,
    {}
  >({ url: "/api/auth/magic-login", method: "get", ...variables, signal });

export type GetMyProfileError = Fetcher.ErrorWrapper<undefined>;

export const getMyProfile = (signal?: AbortSignal) =>
  chronosFetch<Schemas.User, GetMyProfileError, undefined, {}, {}, {}>({
    url: "/api/me/profile",
    method: "get",
    signal,
  });

export type GetMyMembershipsError = Fetcher.ErrorWrapper<undefined>;

export type GetMyMembershipsResponse = Schemas.MyMembership[];

export const getMyMemberships = (signal?: AbortSignal) =>
  chronosFetch<
    GetMyMembershipsResponse,
    GetMyMembershipsError,
    undefined,
    {},
    {},
    {}
  >({ url: "/api/me/memberships", method: "get", signal });

export type GetMembersHeaders = {
  /**
   * Optional organization filter
   */
  ["X-Org-ID"]?: string;
};

export type GetMembersError = Fetcher.ErrorWrapper<undefined>;

export type GetMembersResponse = Schemas.Member[];

export type GetMembersVariables = {
  headers?: GetMembersHeaders;
};

export const getMembers = (
  variables: GetMembersVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    GetMembersResponse,
    GetMembersError,
    undefined,
    GetMembersHeaders,
    {},
    {}
  >({ url: "/api/members", method: "get", ...variables, signal });

export type GetOrganizationsError = Fetcher.ErrorWrapper<undefined>;

export type GetOrganizationsResponse = string[];

export const getOrganizations = (signal?: AbortSignal) =>
  chronosFetch<
    GetOrganizationsResponse,
    GetOrganizationsError,
    undefined,
    {},
    {},
    {}
  >({ url: "/api/organizations", method: "get", signal });

export type GetOrganizationHierarchyError = Fetcher.ErrorWrapper<undefined>;

export type GetOrganizationHierarchyResponse = Schemas.OrgNode[];

export const getOrganizationHierarchy = (signal?: AbortSignal) =>
  chronosFetch<
    GetOrganizationHierarchyResponse,
    GetOrganizationHierarchyError,
    undefined,
    {},
    {},
    {}
  >({ url: "/api/organizations/hierarchy", method: "get", signal });

export type CreateOrganizationError = Fetcher.ErrorWrapper<undefined>;

export type CreateOrganizationVariables = {
  body: Schemas.CreateOrgRequest;
};

export const createOrganization = (
  variables: CreateOrganizationVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    CreateOrganizationError,
    Schemas.CreateOrgRequest,
    {},
    {},
    {}
  >({
    url: "/api/commands/create-organization",
    method: "post",
    ...variables,
    signal,
  });

export type DeleteOrganizationQueryParams = {
  id: string;
};

export type DeleteOrganizationError = Fetcher.ErrorWrapper<undefined>;

export type DeleteOrganizationVariables = {
  queryParams: DeleteOrganizationQueryParams;
};

export const deleteOrganization = (
  variables: DeleteOrganizationVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    DeleteOrganizationError,
    undefined,
    {},
    DeleteOrganizationQueryParams,
    {}
  >({
    url: "/api/commands/delete-organization",
    method: "post",
    ...variables,
    signal,
  });

export type RegisterMemberError = Fetcher.ErrorWrapper<undefined>;

export type RegisterMemberResponse = {
  id?: string;
};

export type RegisterMemberVariables = {
  body: Schemas.RegisterMemberRequest;
};

export const registerMember = (
  variables: RegisterMemberVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    RegisterMemberResponse,
    RegisterMemberError,
    Schemas.RegisterMemberRequest,
    {},
    {},
    {}
  >({
    url: "/api/commands/register-member",
    method: "post",
    ...variables,
    signal,
  });

export type UpdateMemberError = Fetcher.ErrorWrapper<undefined>;

export type UpdateMemberVariables = {
  body: Schemas.UpdateMemberRequest;
};

export const updateMember = (
  variables: UpdateMemberVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    UpdateMemberError,
    Schemas.UpdateMemberRequest,
    {},
    {},
    {}
  >({
    url: "/api/commands/update-member",
    method: "post",
    ...variables,
    signal,
  });

export type ShredMemberError = Fetcher.ErrorWrapper<undefined>;

export type ShredMemberVariables = {
  body: Schemas.ShredMemberRequest;
};

export const shredMember = (
  variables: ShredMemberVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    ShredMemberError,
    Schemas.ShredMemberRequest,
    {},
    {},
    {}
  >({
    url: "/api/commands/shred-member",
    method: "post",
    ...variables,
    signal,
  });

export type GetMembersAsOfQueryParams = {
  /**
   * @format date
   */
  date: string;
};

export type GetMembersAsOfHeaders = {
  ["X-Org-ID"]?: string;
};

export type GetMembersAsOfError = Fetcher.ErrorWrapper<undefined>;

export type GetMembersAsOfResponse = Schemas.Member[];

export type GetMembersAsOfVariables = {
  headers?: GetMembersAsOfHeaders;
  queryParams: GetMembersAsOfQueryParams;
};

export const getMembersAsOf = (
  variables: GetMembersAsOfVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    GetMembersAsOfResponse,
    GetMembersAsOfError,
    undefined,
    GetMembersAsOfHeaders,
    GetMembersAsOfQueryParams,
    {}
  >({ url: "/api/reports/as-of", method: "get", ...variables, signal });

export type GetTreasuryReportError = Fetcher.ErrorWrapper<undefined>;

export type GetTreasuryReportResponse = Schemas.TreasuryItem[];

export const getTreasuryReport = (signal?: AbortSignal) =>
  chronosFetch<
    GetTreasuryReportResponse,
    GetTreasuryReportError,
    undefined,
    {},
    {},
    {}
  >({ url: "/api/reports/treasury", method: "get", signal });

export type GetStatsError = Fetcher.ErrorWrapper<undefined>;

export type GetStatsResponse = Schemas.StatRow[];

export const getStats = (signal?: AbortSignal) =>
  chronosFetch<GetStatsResponse, GetStatsError, undefined, {}, {}, {}>({
    url: "/api/reports/stats",
    method: "get",
    signal,
  });

export type GetFormsQueryParams = {
  org_id?: string;
};

export type GetFormsError = Fetcher.ErrorWrapper<undefined>;

export type GetFormsResponse = Schemas.Form[];

export type GetFormsVariables = {
  queryParams?: GetFormsQueryParams;
};

export const getForms = (variables: GetFormsVariables, signal?: AbortSignal) =>
  chronosFetch<
    GetFormsResponse,
    GetFormsError,
    undefined,
    {},
    GetFormsQueryParams,
    {}
  >({ url: "/api/forms", method: "get", ...variables, signal });

export type SubmitFormError = Fetcher.ErrorWrapper<undefined>;

export type SubmitFormVariables = {
  body: Schemas.FormResponseRequest;
};

export const submitForm = (
  variables: SubmitFormVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    SubmitFormError,
    Schemas.FormResponseRequest,
    {},
    {},
    {}
  >({ url: "/api/commands/submit-form", method: "post", ...variables, signal });
