/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import type * as Fetcher from "./chronosFetcher";
import { chronosFetch } from "./chronosFetcher";
import type * as Schemas from "./chronosSchemas";

export type GetHealthError = Fetcher.ErrorWrapper<undefined>;

export const getHealth = (signal?: AbortSignal) =>
  chronosFetch<undefined, GetHealthError, undefined, {}, {}, {}>({
    url: "/api/health",
    method: "get",
    signal,
  });

export type SignupError = Fetcher.ErrorWrapper<undefined>;

export type SignupResponse = {
  message?: string;
};

export type SignupVariables = {
  body: Schemas.SignupRequest;
};

export const signup = (variables: SignupVariables, signal?: AbortSignal) =>
  chronosFetch<SignupResponse, SignupError, Schemas.SignupRequest, {}, {}, {}>({
    url: "/api/auth/signup",
    method: "post",
    ...variables,
    signal,
  });

export type LoginError = Fetcher.ErrorWrapper<undefined>;

export type LoginVariables = {
  body?: Schemas.AuthResponse;
};

export const login = (variables: LoginVariables, signal?: AbortSignal) =>
  chronosFetch<
    Schemas.AuthResponse,
    LoginError,
    Schemas.AuthResponse,
    {},
    {},
    {}
  >({ url: "/api/auth/login", method: "post", ...variables, signal });

export type RequestMagicLinkError = Fetcher.ErrorWrapper<undefined>;

export type RequestMagicLinkRequestBody = {
  email?: string;
};

export type RequestMagicLinkVariables = {
  body?: RequestMagicLinkRequestBody;
};

export const requestMagicLink = (
  variables: RequestMagicLinkVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    RequestMagicLinkError,
    RequestMagicLinkRequestBody,
    {},
    {},
    {}
  >({
    url: "/api/auth/request-magic-link",
    method: "post",
    ...variables,
    signal,
  });

export type MagicLoginQueryParams = {
  token: string;
};

export type MagicLoginError = Fetcher.ErrorWrapper<undefined>;

export type MagicLoginVariables = {
  queryParams: MagicLoginQueryParams;
};

export const magicLogin = (
  variables: MagicLoginVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    Schemas.AuthResponse,
    MagicLoginError,
    undefined,
    {},
    MagicLoginQueryParams,
    {}
  >({ url: "/api/auth/magic-login", method: "get", ...variables, signal });

export type GetMyProfileError = Fetcher.ErrorWrapper<undefined>;

export const getMyProfile = (signal?: AbortSignal) =>
  chronosFetch<Schemas.User, GetMyProfileError, undefined, {}, {}, {}>({
    url: "/api/me/profile",
    method: "get",
    signal,
  });

export type UpdateMyProfileError = Fetcher.ErrorWrapper<undefined>;

export type UpdateMyProfileRequestBody = {
  name?: string;
  email?: string;
};

export type UpdateMyProfileVariables = {
  body?: UpdateMyProfileRequestBody;
};

export const updateMyProfile = (
  variables: UpdateMyProfileVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    UpdateMyProfileError,
    UpdateMyProfileRequestBody,
    {},
    {},
    {}
  >({ url: "/api/me/profile", method: "put", ...variables, signal });

export type GetMyMembershipsError = Fetcher.ErrorWrapper<undefined>;

export type GetMyMembershipsResponse = Schemas.MyMembership[];

export const getMyMemberships = (signal?: AbortSignal) =>
  chronosFetch<
    GetMyMembershipsResponse,
    GetMyMembershipsError,
    undefined,
    {},
    {},
    {}
  >({ url: "/api/me/memberships", method: "get", signal });

export type GetReactionsQueryParams = {
  org_id: string;
  trigger_aggregate_id?: string;
};

export type GetReactionsError = Fetcher.ErrorWrapper<undefined>;

export type GetReactionsResponse = Schemas.EventReaction[];

export type GetReactionsVariables = {
  queryParams: GetReactionsQueryParams;
};

export const getReactions = (
  variables: GetReactionsVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    GetReactionsResponse,
    GetReactionsError,
    undefined,
    {},
    GetReactionsQueryParams,
    {}
  >({ url: "/api/admin/reactions", method: "get", ...variables, signal });

export type CreateReactionError = Fetcher.ErrorWrapper<undefined>;

export type CreateReactionVariables = {
  body: Schemas.CreateReactionRequest;
};

export const createReaction = (
  variables: CreateReactionVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    CreateReactionError,
    Schemas.CreateReactionRequest,
    {},
    {},
    {}
  >({ url: "/api/admin/reactions", method: "post", ...variables, signal });

export type GetOrgansQueryParams = {
  org_id: string;
};

export type GetOrgansError = Fetcher.ErrorWrapper<undefined>;

export type GetOrgansResponse = Schemas.Organ[];

export type GetOrgansVariables = {
  queryParams: GetOrgansQueryParams;
};

export const getOrgans = (
  variables: GetOrgansVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    GetOrgansResponse,
    GetOrgansError,
    undefined,
    {},
    GetOrgansQueryParams,
    {}
  >({ url: "/api/admin/organs", method: "get", ...variables, signal });

export type CreateOrganError = Fetcher.ErrorWrapper<undefined>;

export type CreateOrganRequestBody = {
  org_id: string;
  name: string;
  parent_organ_id?: string | null;
};

export type CreateOrganVariables = {
  body: CreateOrganRequestBody;
};

export const createOrgan = (
  variables: CreateOrganVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<undefined, CreateOrganError, CreateOrganRequestBody, {}, {}, {}>(
    { url: "/api/admin/organs", method: "post", ...variables, signal },
  );

export type GetOrganMembersQueryParams = {
  organ_id: string;
};

export type GetOrganMembersError = Fetcher.ErrorWrapper<undefined>;

export type GetOrganMembersResponse = Schemas.MemberRole[];

export type GetOrganMembersVariables = {
  queryParams: GetOrganMembersQueryParams;
};

export const getOrganMembers = (
  variables: GetOrganMembersVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    GetOrganMembersResponse,
    GetOrganMembersError,
    undefined,
    {},
    GetOrganMembersQueryParams,
    {}
  >({ url: "/api/admin/organ-members", method: "get", ...variables, signal });

export type AssignOrganMemberError = Fetcher.ErrorWrapper<undefined>;

export type AssignOrganMemberRequestBody = {
  user_id: string;
  organ_id: string;
  role_type: string;
};

export type AssignOrganMemberVariables = {
  body: AssignOrganMemberRequestBody;
};

export const assignOrganMember = (
  variables: AssignOrganMemberVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    AssignOrganMemberError,
    AssignOrganMemberRequestBody,
    {},
    {},
    {}
  >({ url: "/api/admin/organ-members", method: "post", ...variables, signal });

export type RevokeOrganMemberQueryParams = {
  id: string;
};

export type RevokeOrganMemberError = Fetcher.ErrorWrapper<undefined>;

export type RevokeOrganMemberVariables = {
  queryParams: RevokeOrganMemberQueryParams;
};

export const revokeOrganMember = (
  variables: RevokeOrganMemberVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    RevokeOrganMemberError,
    undefined,
    {},
    RevokeOrganMemberQueryParams,
    {}
  >({
    url: "/api/admin/organ-members",
    method: "delete",
    ...variables,
    signal,
  });

export type GetFormResponsesQueryParams = {
  form_id: string;
};

export type GetFormResponsesError = Fetcher.ErrorWrapper<undefined>;

export type GetFormResponsesResponse = Schemas.FormResponse[];

export type GetFormResponsesVariables = {
  queryParams: GetFormResponsesQueryParams;
};

export const getFormResponses = (
  variables: GetFormResponsesVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    GetFormResponsesResponse,
    GetFormResponsesError,
    undefined,
    {},
    GetFormResponsesQueryParams,
    {}
  >({ url: "/api/admin/form-responses", method: "get", ...variables, signal });

export type GetMembersHeaders = {
  /**
   * Optional organization filter
   */
  ["X-Org-ID"]?: string;
};

export type GetMembersError = Fetcher.ErrorWrapper<undefined>;

export type GetMembersResponse = Schemas.Member[];

export type GetMembersVariables = {
  headers?: GetMembersHeaders;
};

export const getMembers = (
  variables: GetMembersVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    GetMembersResponse,
    GetMembersError,
    undefined,
    GetMembersHeaders,
    {},
    {}
  >({ url: "/api/members", method: "get", ...variables, signal });

export type GetOrganizationsError = Fetcher.ErrorWrapper<undefined>;

export type GetOrganizationsResponse = string[];

export const getOrganizations = (signal?: AbortSignal) =>
  chronosFetch<
    GetOrganizationsResponse,
    GetOrganizationsError,
    undefined,
    {},
    {},
    {}
  >({ url: "/api/organizations", method: "get", signal });

export type GetOrganizationHierarchyError = Fetcher.ErrorWrapper<undefined>;

export type GetOrganizationHierarchyResponse = Schemas.OrgNode[];

export const getOrganizationHierarchy = (signal?: AbortSignal) =>
  chronosFetch<
    GetOrganizationHierarchyResponse,
    GetOrganizationHierarchyError,
    undefined,
    {},
    {},
    {}
  >({ url: "/api/organizations/hierarchy", method: "get", signal });

export type RegisterMemberError = Fetcher.ErrorWrapper<undefined>;

export type RegisterMemberResponse = {
  id?: string;
};

export type RegisterMemberVariables = {
  body: Schemas.RegisterMemberRequest;
};

export const registerMember = (
  variables: RegisterMemberVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    RegisterMemberResponse,
    RegisterMemberError,
    Schemas.RegisterMemberRequest,
    {},
    {},
    {}
  >({
    url: "/api/commands/register-member",
    method: "post",
    ...variables,
    signal,
  });

export type UpdateMemberError = Fetcher.ErrorWrapper<undefined>;

export type UpdateMemberVariables = {
  body: Schemas.UpdateMemberRequest;
};

export const updateMember = (
  variables: UpdateMemberVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    UpdateMemberError,
    Schemas.UpdateMemberRequest,
    {},
    {},
    {}
  >({
    url: "/api/commands/update-member",
    method: "post",
    ...variables,
    signal,
  });

export type ShredMemberError = Fetcher.ErrorWrapper<undefined>;

export type ShredMemberVariables = {
  body: Schemas.ShredMemberRequest;
};

export const shredMember = (
  variables: ShredMemberVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    ShredMemberError,
    Schemas.ShredMemberRequest,
    {},
    {},
    {}
  >({
    url: "/api/commands/shred-member",
    method: "post",
    ...variables,
    signal,
  });

export type GetMembersAsOfQueryParams = {
  /**
   * @format date
   */
  date: string;
};

export type GetMembersAsOfHeaders = {
  ["X-Org-ID"]?: string;
};

export type GetMembersAsOfError = Fetcher.ErrorWrapper<undefined>;

export type GetMembersAsOfResponse = Schemas.Member[];

export type GetMembersAsOfVariables = {
  headers?: GetMembersAsOfHeaders;
  queryParams: GetMembersAsOfQueryParams;
};

export const getMembersAsOf = (
  variables: GetMembersAsOfVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    GetMembersAsOfResponse,
    GetMembersAsOfError,
    undefined,
    GetMembersAsOfHeaders,
    GetMembersAsOfQueryParams,
    {}
  >({ url: "/api/reports/as-of", method: "get", ...variables, signal });

export type GetTreasuryReportError = Fetcher.ErrorWrapper<undefined>;

export type GetTreasuryReportResponse = Schemas.TreasuryItem[];

export const getTreasuryReport = (signal?: AbortSignal) =>
  chronosFetch<
    GetTreasuryReportResponse,
    GetTreasuryReportError,
    undefined,
    {},
    {},
    {}
  >({ url: "/api/reports/treasury", method: "get", signal });

export type GetStatsError = Fetcher.ErrorWrapper<undefined>;

export const getStats = (signal?: AbortSignal) =>
  chronosFetch<Schemas.MultiStats, GetStatsError, undefined, {}, {}, {}>({
    url: "/api/reports/stats",
    method: "get",
    signal,
  });

export type GetAuditLogsQueryParams = {
  org_id?: string;
  actor_id?: string;
  target_id?: string;
};

export type GetAuditLogsError = Fetcher.ErrorWrapper<undefined>;

export type GetAuditLogsResponse = Schemas.AuditLogEntry[];

export type GetAuditLogsVariables = {
  queryParams?: GetAuditLogsQueryParams;
};

export const getAuditLogs = (
  variables: GetAuditLogsVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    GetAuditLogsResponse,
    GetAuditLogsError,
    undefined,
    {},
    GetAuditLogsQueryParams,
    {}
  >({ url: "/api/audit/logs", method: "get", ...variables, signal });

export type GetUserProfilePathParams = {
  id: string;
};

export type GetUserProfileError = Fetcher.ErrorWrapper<undefined>;

export type GetUserProfileVariables = {
  pathParams: GetUserProfilePathParams;
};

export const getUserProfile = (
  variables: GetUserProfileVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    Schemas.User,
    GetUserProfileError,
    undefined,
    {},
    {},
    GetUserProfilePathParams
  >({ url: "/api/admin/users/{id}", method: "get", ...variables, signal });

export type GetUserMembershipsPathParams = {
  id: string;
};

export type GetUserMembershipsError = Fetcher.ErrorWrapper<undefined>;

export type GetUserMembershipsResponse = Schemas.MyMembership[];

export type GetUserMembershipsVariables = {
  pathParams: GetUserMembershipsPathParams;
};

export const getUserMemberships = (
  variables: GetUserMembershipsVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    GetUserMembershipsResponse,
    GetUserMembershipsError,
    undefined,
    {},
    {},
    GetUserMembershipsPathParams
  >({
    url: "/api/admin/users/{id}/memberships",
    method: "get",
    ...variables,
    signal,
  });

export type GetFormsQueryParams = {
  org_id?: string;
};

export type GetFormsError = Fetcher.ErrorWrapper<undefined>;

export type GetFormsResponse = Schemas.Form[];

export type GetFormsVariables = {
  queryParams?: GetFormsQueryParams;
};

export const getForms = (variables: GetFormsVariables, signal?: AbortSignal) =>
  chronosFetch<
    GetFormsResponse,
    GetFormsError,
    undefined,
    {},
    GetFormsQueryParams,
    {}
  >({ url: "/api/forms", method: "get", ...variables, signal });

export type CreateFormError = Fetcher.ErrorWrapper<undefined>;

export type CreateFormResponse = {
  id?: string;
};

export type CreateFormVariables = {
  body: Schemas.CreateFormRequest;
};

export const createForm = (
  variables: CreateFormVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    CreateFormResponse,
    CreateFormError,
    Schemas.CreateFormRequest,
    {},
    {},
    {}
  >({ url: "/api/commands/create-form", method: "post", ...variables, signal });

export type UpdateFormError = Fetcher.ErrorWrapper<undefined>;

export type UpdateFormVariables = {
  body: Schemas.UpdateFormRequest;
};

export const updateForm = (
  variables: UpdateFormVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    UpdateFormError,
    Schemas.UpdateFormRequest,
    {},
    {},
    {}
  >({ url: "/api/commands/update-form", method: "post", ...variables, signal });

export type SubmitFormError = Fetcher.ErrorWrapper<undefined>;

export type SubmitFormVariables = {
  body: Schemas.FormResponseRequest;
};

export const submitForm = (
  variables: SubmitFormVariables,
  signal?: AbortSignal,
) =>
  chronosFetch<
    undefined,
    SubmitFormError,
    Schemas.FormResponseRequest,
    {},
    {},
    {}
  >({ url: "/api/commands/submit-form", method: "post", ...variables, signal });
