/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type SignupRequest = {
  email: string;
  password: string;
  org_id?: string;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type AuthResponse = {
  access_token?: string;
  user?: User;
};

export type OrgNode = {
  id: string;
  name: string;
  parent_id?: string | null;
  path: string;
  policy?: {
    [key: string]: any;
  };
};

export type CreateOrgRequest = {
  name: string;
  parent_id?: string;
  policy?: {
    [key: string]: any;
  };
};

export type UpdateFormRequest = {
  id: string;
  title?: string;
  schema?: {
    [key: string]: any;
  };
};

export type User = {
  id?: string;
  email?: string;
  name?: string;
  /**
   * @format date-time
   */
  created_at?: string;
};

export type MyMembership = {
  id?: string;
  org_id?: string;
  org_name?: string;
  status?: string;
  role?: string;
  balance?: number;
  /**
   * @format date-time
   */
  updated_at?: string;
};

export type EventReaction = {
  id?: string;
  org_id?: string;
  trigger_event?: string;
  trigger_aggregate_id?: string | null;
  action_type?: string;
  config?: {
    [key: string]: any;
  };
  is_inherited?: boolean;
};

export type CreateReactionRequest = {
  org_id: string;
  trigger_event: string;
  trigger_aggregate_id?: string;
  action_type: string;
  config: {
    [key: string]: any;
  };
};

export type Organ = {
  id?: string;
  org_id?: string;
  name?: string;
  parent_organ_id?: string | null;
  member_count?: number;
};

export type MemberRole = {
  id?: string;
  user_id?: string;
  role_type?: string;
  name?: string;
  email?: string;
  /**
   * @format date-time
   */
  created_at?: string;
};

export type Form = {
  id?: string;
  org_id?: string;
  title?: string;
  schema?: {
    [key: string]: any;
  };
};

export type FormResponseRequest = {
  form_id: string;
  answers: {
    [key: string]: any;
  };
};

export type CreateFormRequest = {
  org_id: string;
  title: string;
  schema: {
    [key: string]: any;
  };
};

export type MultiStats = {
  new_members?: StatRow[];
  churn?: StatRow[];
  total_active?: StatRow[];
  payments?: StatRow[];
};

export type StatRow = {
  label: string;
  value: number;
};

export type TreasuryItem = {
  id: string;
  name: string;
  path: string;
  local_balance: number;
  total_branch_balance: number;
};

export type AuditLogEntry = {
  id?: string;
  correlation_id?: string;
  action?: string;
  target_id?: string | null;
  detail?: {
    [key: string]: any;
  };
  ip_address?: string;
  user_agent?: string;
  /**
   * @format date-time
   */
  created_at?: string;
  actor_email?: string | null;
  org_name?: string | null;
};

export type Member = {
  id?: string;
  user_id?: string;
  org_id?: string;
  name?: string;
  email?: string;
  status?: string;
  metadata?: {
    [key: string]: any;
  };
  balance?: number;
  fee_formula?: string;
  /**
   * @format date-time
   */
  created_at?: string;
  /**
   * @format date-time
   */
  updated_at?: string;
};

export type RegisterMemberRequest = {
  name: string;
  email: string;
  org_id?: string;
  metadata?: {
    [key: string]: any;
  };
};

export type UpdateMemberRequest = {
  id: string;
  updated_fields: {
    [key: string]: any;
  };
};

export type ShredMemberRequest = {
  id: string;
};
