/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type SignupRequest = {
  email: string;
  password: string;
  org_id?: string;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type AuthResponse = {
  access_token?: string;
  user?: User;
};

export type OrgNode = {
  id?: string;
  name?: string;
  parent_id?: string | null;
  path?: string;
  policy?: {
    [key: string]: any;
  };
};

export type CreateOrgRequest = {
  name: string;
  parent_id?: string;
  policy?: {
    [key: string]: any;
  };
};

export type User = {
  id?: string;
  email?: string;
  name?: string;
  /**
   * @format date-time
   */
  created_at?: string;
};

export type MyMembership = {
  id?: string;
  org_id?: string;
  org_name?: string;
  status?: string;
  role?: string;
  balance?: number;
  /**
   * @format date-time
   */
  updated_at?: string;
};

export type Form = {
  id?: string;
  org_id?: string;
  title?: string;
  schema?: {
    [key: string]: any;
  };
};

export type FormResponseRequest = {
  form_id: string;
  answers: {
    [key: string]: any;
  };
};

export type CreateFormRequest = {
  org_id: string;
  title: string;
  schema: {
    [key: string]: any;
  };
};

export type StatRow = {
  label?: string;
  value?: number;
};

export type TreasuryItem = {
  id?: string;
  name?: string;
  path?: string;
  local_balance?: number;
  total_branch_balance?: number;
};

export type Member = {
  id?: string;
  org_id?: string;
  name?: string;
  email?: string;
  status?: string;
  metadata?: {
    [key: string]: any;
  };
  balance?: number;
  fee_formula?: string;
  /**
   * @format date-time
   */
  created_at?: string;
  /**
   * @format date-time
   */
  updated_at?: string;
};

export type RegisterMemberRequest = {
  name: string;
  email: string;
  org_id?: string;
  metadata?: {
    [key: string]: any;
  };
};

export type UpdateMemberRequest = {
  id: string;
  updated_fields: {
    [key: string]: any;
  };
};

export type ShredMemberRequest = {
  id: string;
};
